### ISSUE TITLE
Add 'Work at a Startup'

### ISSUE THREAD

**Issue by mithintv** [mithintv/job-scraper#1]
### Tasks

- [x] Grab job title
- [x] Grab job company
- [x] Grab job location
- [x] Grab job salary
- [x] Label as 'Work at a Startup'
